config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # いいね機能関係のルーティング
  # いいね機能 as: で prefix名　を指定できます
  post   '/like/:review_id' => 'likes#like',   as: 'like'
  delete '/like/:review_id' => 'likes#unlike', as: 'unlike'

  # path無しの時のトップページへリダイレクト
  root    'reviews#index'


  # メインのルーティング
  resources :arts, only:[:index, :show, :create, :new, :edit, :update] do
    resources :reviews, only:[:index, :show, :new, :create] do
      resources :chats, only:[:create]
    end
  end

    # 投稿後のリダイレクトが上手く行かなかったため、個別で定義している
    get '/arts/:art_id/reviews/:review_id' => 'reviews#show', as: 'redirect_chat'

# ログアウト？
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :review, counter_cache: :likes_count
  # counter_cache:＝＞リレーションされているlikeの数の値をリレーション先のlikes_countというカラムの値に入れます
  # likes_countカラム=>review_tableに追加OK
  belongs_to :user
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
# ・set_variablesで変数を定義しています。@id_nameは非同期の時に使います。
  before_action :set_variables

  def like
# Userモデルの呼び出しをcurrent_userで行うことで、自動的にuser_idにcurrent_user.idが指定されます。
# likesテーブルの「user_id」と「review_id」を保存する
    like = current_user.likes.new(review_id: @review.id)
    like.save
  end

  def unlike
# likesテーブルの「user_id」と「review_id」を削除する
    like = current_user.likes.find_by(review_id: @review.id)
    like.destroy
  end

  private

  def set_variables
    @review = Review.find(params[:review_id])
    @id_name = "#like-link-#{@review.id}"
  end

end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like.html.erb
<%# いいね機能押してない時(１＝＞０) %>
<div class="like-link" id="like-link-<%= review.id %>">
  <% if current_user.likes.find_by(review_id: review.id) %>
    <%= link_to unlike_path(review.id), method: :delete, remote: true do %>
        <div class = "iine__button">❤️<%= review.likes.count %></div>
    <% end %>
<%# いいね機能押してない時(０＝＞１) %>
  <% else %>
    <%= link_to like_path(review.id), method: :post, remote: true do %>
        <div class = "iine__button">♡️<%= review.likes.count %></div>
    <% end %>
  <% end %>
</div>

app/views/likes/like.js.erb
$("<%= @id_name %>").html('<%= escape_javascript(render("likes/like", review: @review  )) %>');

app/views/likes/unlike.js.erb
$("<%= @id_name %>").html('<%= escape_javascript(render("likes/like", review: @review  )) %>');