config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # いいね機能関係のルーティング
  # いいね機能 as: で prefix名　を指定できます
  post   '/like/:review_id' => 'likes#like',   as: 'like'
  delete '/like/:review_id' => 'likes#unlike', as: 'unlike'

  # path無しの時のトップページへリダイレクト
  root    'reviews#index'


  # メインのルーティング
  resources :arts, only:[:index, :show, :create, :new, :edit, :update] do
    resources :reviews, only:[:index, :show, :new, :create] do
      resources :chats, only:[:create]
    end
  end

    # 投稿後のリダイレクトが上手く行かなかったため、個別で定義している
    get '/arts/:art_id/reviews/:review_id' => 'reviews#show', as: 'redirect_chat'

# ログアウト？
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :login_check

  # トップページ(レビューと、そのランキングを表示)
  def index
    @reviews = Review.order("id DESC")
    @reviews_rank = Review.order("likes_count ASC")
  end

  # レビュー詳細画面(コメントができる)
  def show
    # チャットのフォームから送信した場合、パラメーターのkeyが通常の(id)から(review_id)となるため、if文を仕様している
    if params[:id] then
      @review = Review.find(params[:id])
    elsif params[:review_id] then
     @review = Review.find(params[:review_id])
    end
    # チャットへ投稿内容を表示するため、chatsのインスタンス変数を定義している
    @chats = @review.chats
  end

  # レビューの投稿画面
  def new
    @review = Review.new
  end

  # レビューの保存ロジック
  def create
    @review = Review.new(title: review_params[:title], content: review_params[:content], image: review_params[:image], art_id: params[:art_id], user_id: current_user.id)
    @review.save

    if @review.save
      # artsコントローラーのshowアクションに飛ぶがidが渡せないので付与
      redirect_to action: 'index'
   else
     render :new
   end

  end

  # ログインしていないとログイン画面しか行けない設定
  def login_check
    redirect_to  "/users/sign_in" unless user_signed_in?
  end


  # レビュー投稿のストロングパラメータ＾
  private
  def review_params
    #permitメソッドで変更を加えられる（保存の処理ができる）キーを指定します。
    params.require(:review).permit(:title, :content, :image) # POINT
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_reviews.html.erb
<%= render 'likes/like', review: review %>

app/views/reviews/index.html.erb
<%# react導入後、コンソールに表示されるか実験 %>
<%= javascript_pack_tag 'application' %>

<%# 投稿一覧(左側のコンテンツ) %>
<div class="left_contents">
  <ul>
    <% @reviews.each do |review| %>
      <li>
        <div class="left_contents-tweet">
            <%# タイトル表示 %>
            <div class="left_contents-tweet_title">
            <%# ログを表示させる(ホーム画面に繊維するaタグを付与) %>
            <a href="/arts/<%= review.art.id %>/reviews/<%= review.id %>">
                <span><%= review.title %></span>
            </a>
            </div>

            <%# 作品名を表示(作品詳細ページへ画面遷移) %>
            <div>
            <a href="/arts/<%= review.art_id %>">
                <span><%= review.art.title %></span>
            </a>
            </div>

            <%# いいねのテンプレートを呼び出し(作品のidを使いたいのでreviewを受け渡します) %>
            <%= render partial: 'reviews/reviews', :locals => { review: review } %>

            <%# レビューの画像を表示する %>
            <div class="left_contents-tweet_main">
              <%= image_tag(review.image) %>
            </div>

        <%# class="left_contents-tweet"の閉じタグ %>
        </div>

        <%# レビューのレビュー内容(テキスト)を表示 %>
        <div class="left_contents_text">
          <h1><%= review.content %></h1>
        </div>

        <%# 投稿したユーザーのニックネイムを表示 %>
        <span><%= review.user.nickname %></span>
      </li>
    <% end %>
  </ul>
</div>



<%# オススメ画面(右側のコンテンツ) %>
<div class="right_contents">

  <div class="right_contents-recommended_title">
    <h1 class="right_contents-recommended_title_font">オススメ</h1>
  </div>

  <ul>
    <%# いいね順で取得した@reviews_rankを使用 %>
    <% @reviews_rank.each do |review| %>
      <li>
        <div class="right_contents-recommended_main">
            <div class="right_contents-recommended_main_image">
            <%= image_tag(review.image) %>
            <%= review.title %>
            </div>
        </div>
      </li>
    <% end %>
  </ul>

</div>

app/views/reviews/new.html.erb
<div class="reviews_new">
  <div class="reviews_new_content">

    <%# レビューの投稿フォームを作成 %>
    <%= form_with model: [@art, @review],url: art_reviews_path, local: true  do |form| %>


    <%# バリデーションにかかり、エラーがあればエラーメッセージを表示 %>
     <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= @review.errors.count %> 箇所のエラーがあります。下記を確認して下さい:</h2>
      <ul>
      <% @review.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<%# 改行 %>
  <br>
  <br>



    <div class="reviews_new_content_title">
      <h1>レビューのタイトルを入力してください</h1>
      <%= form.text_field :title, :size => '60'%><br>
    </div>

    <div class="reviews_new_content_content">
      <h1>レビューを入力してください</h1>
      <%= form.text_area :content %><br>
    </div>

    <div class="reviews_new_content_image">
      <%= form.label :image %>
      <%= form.file_field :image %>
    </div>

    <div class="reviews_new_content_submit">
      <%= form.submit %>
    </div>

    <% end %>
  </div>
</div>

app/views/reviews/show.html.erb
<div class="show_main">
    <div class="show_main_content">
      <div class="show_main_content_title">
        <h1><%= @review.title %></h1>
      </div>

      <div class="show_main_content_main">
        <%= image_tag(@review.image) %>
      </div>

    </div>

    <div class="show_main_content_text">
      <h1><%= @review.content %></h1>
    </div>

    <div class="show_main_text-box"></div>

    <div class="show_main_chat">
      <%= form_tag("/arts/#{@review.art_id}/reviews/#{@review.id}/chats", method: :post) do %>
        <textarea name="text" placeholder="コメントする" rows="2" cols="30"></textarea>
        <input type="submit" value="SENT">
      <% end %>

      <ul>
      <% @chats.each do |chat| %>
        <li>
          <h1><%= chat.text %></h1>
        </li>
      <% end %>
      </ul>
    </div>
</div>