config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # いいね機能関係のルーティング
  # いいね機能 as: で prefix名　を指定できます
  post   '/like/:review_id' => 'likes#like',   as: 'like'
  delete '/like/:review_id' => 'likes#unlike', as: 'unlike'

  # path無しの時のトップページへリダイレクト
  root    'reviews#index'


  # メインのルーティング
  resources :arts, only:[:index, :show, :create, :new, :edit, :update] do
    resources :reviews, only:[:index, :show, :new, :create] do
      resources :chats, only:[:create]
    end
  end

    # 投稿後のリダイレクトが上手く行かなかったため、個別で定義している
    get '/arts/:art_id/reviews/:review_id' => 'reviews#show', as: 'redirect_chat'

# ログアウト？
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Artra</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="header_contents">     <!--[固定のヘッダー]-->
        <div>
        <%= link_to  "Artra", "/", {class:"header_contents_logo"} %>   <!--ロゴ-->
        </div>
        <div class="header_contents_button">
          <% if user_signed_in? %>
          <%= link_to  "ログアウト", destroy_user_session_path, {class:"header_contents_button_sign_out"} %>   <!--ログアウト-->
          <%= link_to  "作品追加", new_art_path, {class: "header_contents_button_new"}  %>   <!--検索ボタン-->
          <% else %>
          <%= link_to  "ログイン", user_session_path, {class:"header_contents_button_sign_in"} %>   <!--ログイン-->
          <% end %>
          <%= link_to  "検索", arts_path, {class: "header_contents_button_search"}  %>   <!--検索ボタン-->
        </div>
      </div>
    </header>
    <div class="main">
        <%= yield %>
    </div>
  </body>
</html>